<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930173335" tests="2" time="0.043">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.021"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_prefx_split" time="0.022">
		<error message="0" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 56, in test_prefx_split
    logging.error(data[0])
KeyError: 0
]]>		</error>
	</testcase>
</testsuite>
