<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="2" name="SimpleBalancerOnlyTest.SimpleBalancerInitTest-20151020145818" tests="2" time="0.099">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testInit" time="0.064">
		<failure message="56 != 566" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 41, in testInit
    self.assertEquals(len(flows), 566)
AssertionError: 56 != 566
]]>		</failure>
	</testcase>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testSimpleBalance" time="0.035">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 103, in testSimpleBalance
    self.assertTrue( len(flows) == 566)
AssertionError
]]>		</failure>
	</testcase>
</testsuite>
