<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="5" failures="0" name="SciPassTest.TestFunctionality-20151020151159" tests="5" time="0.005">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SciPassTest.TestFunctionality" name="test_bad_flow" time="0.001">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 194, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
	<testcase classname="SciPassTest.TestFunctionality" name="test_block_unknown_prefix" time="0.001">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 194, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
	<testcase classname="SciPassTest.TestFunctionality" name="test_bypass_unknown_prefix" time="0.001">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 194, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
	<testcase classname="SciPassTest.TestFunctionality" name="test_good_flow" time="0.001">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 194, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
	<testcase classname="SciPassTest.TestFunctionality" name="test_update_prefix_bw" time="0.001">
		<error message="1" type="SystemExit">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SciPassTest.py", line 194, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 59, in __init__
    self._validateConfig(self.configFile, self.schemaFile)
  File "./SciPass.py", line 454, in _validateConfig
    sys.exit(1)
SystemExit: 1
]]>		</error>
	</testcase>
</testsuite>
