<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="5" failures="0" name="ConfigTest.TestPrefix-20151007153928" tests="5" time="0.042">
	<properties/>
	<system-out>
<![CDATA[[{'description': 'lan int',
  'name': 'foo8',
  'port_id': '1',
  'prefixes': [{'prefix': IPv4Network('10.0.17.0/24'),
                'prefix_str': '10.0.17.0/24',
                'type': 'v4'},
               {'prefix': IPv4Network('10.0.18.0/24'),
                'prefix_str': '10.0.18.0/24',
                'type': 'v4'}],
  'vlan_tag': None},
 {'description': 'another lan int',
  'name': 'foo12',
  'port_id': '2',
  'prefixes': [{'prefix': IPv4Network('10.0.19.0/24'),
                'prefix_str': '10.0.19.0/24',
                'type': 'v4'},
               {'prefix': IPv4Network('10.0.20.0/24'),
                'prefix_str': '10.0.20.0/24',
                'type': 'v4'},
               {'prefix': IPv6Network('::/128'),
                'prefix_str': '::/128',
                'type': 'v6'}],
  'vlan_tag': None}]
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_add_prefix" time="0.029">
		<error message="'groups'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 80, in test_add_prefix
    prefixes = data["switch"]["%016x" % self.datapath.id]["domain"]["R&E"]["groups"]["group1"]["prefixes"]
KeyError: 'groups'

Stdout:
[{'description': 'lan int',
  'name': 'foo8',
  'port_id': '1',
  'prefixes': [{'prefix': IPv4Network('10.0.17.0/24'),
                'prefix_str': '10.0.17.0/24',
                'type': 'v4'},
               {'prefix': IPv4Network('10.0.18.0/24'),
                'prefix_str': '10.0.18.0/24',
                'type': 'v4'}],
  'vlan_tag': None},
 {'description': 'another lan int',
  'name': 'foo12',
  'port_id': '2',
  'prefixes': [{'prefix': IPv4Network('10.0.19.0/24'),
                'prefix_str': '10.0.19.0/24',
                'type': 'v4'},
               {'prefix': IPv4Network('10.0.20.0/24'),
                'prefix_str': '10.0.20.0/24',
                'type': 'v4'},
               {'prefix': IPv6Network('::/128'),
                'prefix_str': '::/128',
                'type': 'v6'}],
  'vlan_tag': None}]
]]>		</error>
	</testcase>
	<testcase classname="ConfigTest.TestPrefix" name="test_del_prefix" time="0.003">
		<error message="'prefixes'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 21, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 52, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 527, in _processConfig
    self.readState(dpid, domain)
  File "./SciPass.py", line 539, in readState
    for prefix in data["switch"][switch]["domain"][domain]["prefixes"]:
KeyError: 'prefixes'
]]>		</error>
	</testcase>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.003">
		<error message="'prefixes'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 21, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 52, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 527, in _processConfig
    self.readState(dpid, domain)
  File "./SciPass.py", line 539, in readState
    for prefix in data["switch"][switch]["domain"][domain]["prefixes"]:
KeyError: 'prefixes'
]]>		</error>
	</testcase>
	<testcase classname="ConfigTest.TestPrefix" name="test_move_prefix" time="0.003">
		<error message="'prefixes'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 21, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 52, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 527, in _processConfig
    self.readState(dpid, domain)
  File "./SciPass.py", line 539, in readState
    for prefix in data["switch"][switch]["domain"][domain]["prefixes"]:
KeyError: 'prefixes'
]]>		</error>
	</testcase>
	<testcase classname="ConfigTest.TestPrefix" name="test_sensor_prefix_split" time="0.003">
		<error message="'prefixes'" type="KeyError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 21, in setUp
    config = str(os.getcwd()) + "/t/etc/SciPass.xml" )
  File "./SciPass.py", line 52, in __init__
    self._processConfig(self.configFile)
  File "./SciPass.py", line 527, in _processConfig
    self.readState(dpid, domain)
  File "./SciPass.py", line 539, in readState
    for prefix in data["switch"][switch]["domain"][domain]["prefixes"]:
KeyError: 'prefixes'
]]>		</error>
	</testcase>
</testsuite>
