<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="SimpleBalancerOnlyTest.SimpleBalancerInitTest-20151020143508" tests="1" time="0.053">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="SimpleBalancerOnlyTest.SimpleBalancerInitTest" name="testInit" time="0.053">
		<error message="local variable 'i' referenced before assignment" type="UnboundLocalError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/SimpleBalancerOnlyTest.py", line 40, in testInit
    self.api.switchJoined(datapath)
  File "./SciPass.py", line 687, in switchJoined
    self._setupBalancer(dpid = dpid, domain_name = domain_name)
  File "./SciPass.py", line 894, in _setupBalancer
    self.config[dpid][domain_name]['balancer'].pushToSwitch()
  File "./SimpleBalancer.py", line 120, in pushToSwitch
    self.distributePrefixes(self.prefix_list)
  File "./SimpleBalancer.py", line 245, in distributePrefixes
    i=i+1
UnboundLocalError: local variable 'i' referenced before assignment
]]>		</error>
	</testcase>
</testsuite>
