<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="ConfigTest.TestPrefix-20150930184007" tests="2" time="0.062">
	<properties/>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
	<testcase classname="ConfigTest.TestPrefix" name="test_initial_config" time="0.030"/>
	<testcase classname="ConfigTest.TestPrefix" name="test_prefx_split" time="0.032">
		<error message="list.remove(x): x not in list" type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/home/saikappa/workspace/SciPass/python/t/ConfigTest.py", line 53, in test_prefx_split
    self.api.getBalancer("%016x" % self.datapath.id, "R&E").splitSensorPrefix("group4",ipaddr.IPv4Network("10.0.17.0/24"))
  File "./SimpleBalancer.py", line 518, in splitSensorPrefix
    self.delGroupPrefix(group, candidatePrefix)
  File "./SimpleBalancer.py", line 431, in delGroupPrefix
    self.groups[group]['prefixes'].remove(targetPrefix)
ValueError: list.remove(x): x not in list
]]>		</error>
	</testcase>
</testsuite>
